routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/tampil','hallo@index');
Route::get('/tambah','hallo@create');
Route::get('/edit/{id}','hallo@edit');
Route::get('/hapus/{id}','hallo@hapus');
Route::post('/update','hallo@update');

Route::resource('/hallo', 'hallo');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/model_siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class model_siswa extends Model
{
    protected $table = 'siswa_latihan';

    protected $fillable =[
    	'nama'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/hallo.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\model_siswa;

class hallo extends Controller
{
    public function index()
    {
        $pegawai = DB::table('siswa_latihan')->get();
        return view('index',['siswa_latihan'=>$pegawai]);
    }
    public function create()
    {
    	return view('form');
    }
    public function edit($id)
    {
        $pegawai = DB::table('siswa_latihan')->where('id',$id)->get();
        return view('edit',['edit' => $pegawai]);
    }
    public function store(Request $request)
    {
    	model_siswa::create($request->all());
        return redirect('/tampil');
    }

    public function update(Request $request)
    {
        DB::table('siswa_latihan')->where('id',$request->id)->update([
            'nama' => $request->nama
        ]);
        return redirect('/tampil');
    }
    public function hapus($id)
    {
        DB::table('siswa_latihan')->where('id',$id)->delete();
        return redirect('/tampil');
    }
}

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<form action="/update" method="POST">
	{{ csrf_field() }}
	@foreach($edit as $x)
	<input type="" name="id" value="{{ $x->id }}" hidden="">	
	<input type="" name="nama" value="{{ $x->nama }}">	
	<input type="submit" value="Simpan Data">
	@endforeach
</form>
@endsection

resources/views/form.blade.php
@extends('layouts.app')

@section('content')
<form action="{{ route('hallo.store') }}" method="POST">
	@csrf
	<label>nama:</label>
	<input type="text" name="nama">
	<br>
	<input type="submit" name="" value="submit">
</form>
@endsection

resources/views/index.blade.php
@extends('layouts/app')

@section('content')
<table border="1">
	<tr>
		<th>id</th>
		<th>Nama</th>
		<th>Aksi</th>
	</tr>
	@foreach($siswa_latihan as $x)
	<tr>
		<td>{{ $x->id }}</td>
		<td>{{ $x->nama }}</td>
		<td>
			<a href="/edit/{{ $x->id }}">Edit</a>
			<a href="/hapus/{{ $x->id }}">Hapus</a>
		</td>
	</tr>
	@endforeach
</table>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<ul>
		<li><a href="/tampil">Home</a></li>
		<li><a href="/tambah">+ Tambah</a></li>
	</ul>
	@yield('content')
</body>
</html>